### ISSUE TITLE
Categories picklist value as per Event Type From Event Details Object

### ISSUE THREAD

**Issue by mahesht-mrk** [somnath-flynaut/GitEventManagementProject#50]
As a user, wants to categorize  Event Type into two broad categories—Virtual and Non-Virtual—to ensure that when a user selects Event Type (Virtual and Non-Virtual) in any picklist value, only relevant values should be displayed in a second picklist naming as Event Categories . 

when user select Event Categories as“Corporate Event” then value should visible like (Conference, Seminar, Workshop, Product Launch, Trade Show, Business Meeting) in another dependent picklist Name is  Event Subcategory This setup will make it easy to accurately record event information based on the nature and purpose of each event.

Note:- Create Picklist field name as **Event Subcategory.**

Virtual Values:-
Corporate Event (Conference, Seminar, Workshop, Product Launch, Trade Show, Business Meeting)
Educational Event (Training, Webinar, Lecture, Workshop)
Entertainment Event (Concert, Comedy Show, Movie Screening, Theater Play)

Non-Virtual :-
Social Event (Wedding, Birthday Party, Anniversary Celebration, Reunion)
Cultural Event (Festival, Art Exhibition, Cultural Fair, Heritage Event)
Charity Event (Fundraiser, Charity Ball, Auction, Charity Walk/Run)
Private Event (VIP Gathering, Private Dinner, Private Party)

**Comment by RushikeshFlynaut** [comment]
@nikhilb-sf Please Push your updated layout because updated fields are not visible in QA Org
