### ISSUE TITLE
Enhance Feedback__c Object with Updated Field Labels and Contact Information

### ISSUE THREAD

**Issue by RushikeshFlynaut** [somnath-flynaut/GitEventManagementProject#72]
User Stories:- 
1)Rename “Follow-Up” Checkbox field on Feedback__c object with “Interested in Hosting an Event”

2) Create 2 fields on Feedback__c object as Follows:-

Name__c (Text)
Phone__c(Phone)

3)Add Format validation for Phone__c Field

**Comment by nikhilb-sf** [comment]
Format validation details are not clearly mentioned for Phone__c
