### ISSUE TITLE
Event Team Member Notification with Event Details

### ISSUE THREAD

**Issue by mahesht-mrk** [somnath-flynaut/GitEventManagementProject#75]
**Event Team Member Notification with Event Details:-**

Flow API:- Validate_10_Digit_Phone_Number(By Flow).

Event Team Member Contact phone number must pass a 10-digit validation. If the user attempts to enter a phone number with 11 digits or 9 digits, an error message will be displayed on the field stating: "Please enter a valid 10-digit mobile number."

With Country Code: +91 9876543210 (For only India)

When an **Event Team Member** is selected in the **Event Details** lookup on  (Event Team Member), the Event **Start Date**(Event Detail) and Event **End Date**(Event Detail) fields should be automatically populated with the **Event Team member** Object,  **Start Date and End Date**,  and also **Event Manager** respectively.

T2: **Sending an Email to Event Team Members(trigger)**
 
If an Event Team Member is associated with any **Event Detail and Event Manager record**, or if any event is planned or has an upcoming schedule:
An email should be sent to that team member, including the following details:
Event Detail Name
Event Start Date
Event End Date
Venues 
Event Manager.
Event Manager Name
Event Manager  Phone Number
Event Manager Email

T3

For event team member if we change Event Details field then new record should be created with same name as Event old record (Name, Email, Contact information) and other field as a new (event start date and Event End Date).

**Comment by mahesht-mrk** [comment]
> **Event Team Member Notification with Event Details:-**
> 
> When an **Event Team Member** is selected in the **Event Details** lookup on (Event Team Member), the Event **Start Date**(Event Detail) and Event **End Date**(Event Detail) fields should be automatically populated with the **Event Team member** Object, **Start Date and End Date**, respectively.
> 
> T3: **Sending an Email to Event Team Members(trigger)**
> 
> If an Event Team Member is associated with any **Event Detail and Event Manager record**, or if any event is planned or has an upcoming schedule: An email should be sent to that team member, including the following details: Event Detail Name Event Start Date Event End Date Venues Event Manager. Event Manager Name Event Manager Phone Number Event Manager Email

**Email Format:-** 
Subject: Event Details and Schedule Information

Dear [Event Team Member Name],
You have been assigned to the following event:

Event Details:
Event Name: [Event Detail Name]
Start Date: [Event Start Date]
End Date: [Event End Date]
Venue: [Venue Details]
Event Manager Contact:
Name: [Event Manager Name]
Phone: [Event Manager Phone Number]
Email: [Event Manager Email]

Please reach out to the Event Manager for further details or clarifications.

Best regards,
[Your Organization/Event Team]

**Comment by dreamankita** [comment]
@mahesht-mrk , @somnath-flynaut - I have Done with the flow , Testing, push to the Group-B branch and Merging also done.

**Comment by dreamankita** [comment]
@somnath-flynaut 
Validation Updated in Event Team Member Flow , Deployment done in Branch and Merging Done as well.

**Comment by mahesht-mrk** [comment]
Bugs related to Event Team Member Notification with Event Details
[#75](https://github.com/somnath-flynaut/GitEventManagementProject/issues/75)

Event Team Member -

1)At time of creation send email to event team member about event details and event manger details
2)Whenever Any field changes of event team member (ex- Email, Contact Information) send email to event team member on update as well.
3) Change subject of updated record as - "Event_Team_Member_Name" Your "Event_Detail_Name" is Updated.
