### ISSUE TITLE
Automatically Create a Lead from Feedback with Complete Contact Details and Event Information

### ISSUE THREAD

**Issue by RushikeshFlynaut** [somnath-flynaut/GitEventManagementProject#83]
- User Story:-

    As a Salesforce user, I want to automatically create a Lead when the “Interested in Hosting an Event” checkbox is checked and both the Name and Contact Details are provided, including the Event Name in the Lead Description, so that the team can follow up with the person who provided feedback, ensuring all relevant details are captured in the Lead Description.

- Scenario: Creating Lead from Feedback Submission:-

- Pre-requisite: Add "Feedback" as a picklist value to the Lead Source field on the Lead object.

- Given:A user is creating or updating a Feedback record with “Interested in Hosting an Event” checked, and both Name and Contact Details are provided.

- When:The “Interested in Hosting an Event” checkbox is checked Name and Contact Details fields are not empty

- Then:A Lead is created with the following:

   1)Lead Name: Name provided in the Feedback record
   2)Phone: Phone from the Feedback record
   3)Description: The Event Name from the Feedback object and any relevant Comments or Suggestions
   4)Lead Status: Open-NonContacted picklist value
   5)Lead Source: Feedback
   6)Company: Copy Name in it as it is required  Field on Lead Object

**Comment by RushikeshFlynaut** [comment]
**Updated Scenario**
Given:A user is creating Feedback record with “Interested in Hosting an Event” checked, a Lead should be created 
_Only works in Insert Operation_

**Comment by somnath-flynaut** [comment]
Feedback value of Lead_source picklist value is not visible , that's why we open the issue

**Comment by mahesht-mrk** [comment]
Pull in Developer Branch
